spring:
    profiles:
        active: dev
    application:
        name: "Demo"
        version: "0.1"
---
spring:
    config:
        activate:
            on-profile: dev
server:
    port: 8080
---
spring:
    config:
        activate:
            on-profile: production
server:
    port: 9001
---
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/student
        username: postgres
        password: 20042005kmA
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
---
jwt:
    secret: XX
    access:
        duration:
            minute: 5
            second: 300
        cookie-name: access-token
    refresh:
        duration:
            day: 7
            second: 604800
        cookie-name: refresh-token